name: Setup
description: 'Setup dotnet'

inputs:
  dotnet_version:
    description: 'dotnet version'
    required: true
runs:
  using: 'composite'
  steps:
    
    - name: Checkout
      uses: actions/checkout@v3.3.0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: $dotnet_version
    
    - name: Restore dependencies
      shell: bash
      run: dotnet restore