name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      if: failure()
      with:
        name: logfile
        path: "**/logs/log.txt"
        retention-days: 1
