name: CI

on:
  pull_request:
    branches: [ main ]
  
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:

      - name: Checkout
        uses: actions/checkout@v3.3.0
      
      - name: validate branch name
        uses: ./.github/workflows/validate-branch-name
        with:
          branch_name: ${{ github.head_ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        shell: bash
        run: dotnet restore
        
      - name: build
        run: dotnet build --no-restore --configuration Release

      - name: test
        run: dotnet test /p:Configuration=Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: upload coverage reports to codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

      - name: upload Logs From Failure Run
        uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: logfile
          path: "**/logs/log.txt"
          retention-days: 1