name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
      
      - name: validate branch name
        uses: .github/workflows/validate-branch-name

      - name: setup dotnet
      - uses: .github/workflows/setup
        
      - name: build
        run: dotnet build --no-restore --configuration Release

      - name: test
        run: dotnet test /p:Configuration=Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: upload coverage reports to codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

      - name: upload Logs From Failure Run
        uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: logfile
          path: "**/logs/log.txt"
          retention-days: 1